# Generated by Django 4.2.11 on 2024-10-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, choices=[('PC', 'PC'), ('PS', 'PlayStation'), ('XBOX', 'Xbox'), ('NS', 'Nintendo Switch')], max_length=50, null=True)),
                ('developer', models.CharField(blank=True, max_length=100, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
