# Generated by Django 4.2.11 on 2024-10-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='home.game'),
        ),
    ]
