# Generated by Django 4.2.16 on 2024-10-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_event_options_event_user'),
        ('home', '0005_game_color'),
    ]

    operations = [
    ]
