# Generated by Django 4.2.16 on 2024-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20241027_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
