# Generated by Django 4.2.16 on 2024-11-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_game_picture_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
