# Generated by Django 4.2.16 on 2024-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_event_recurrence_event_recurrence_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
