# Generated by Django 4.2.16 on 2024-11-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_game_picture_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture_upload',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
