# Generated by Django 4.2.16 on 2024-11-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_calendaraccess'),
        ('home', '0010_alter_game_picture_upload'),
    ]

    operations = [
    ]
